version: "{branch}-ci-{build}"

image:
- Visual Studio 2015
- Visual Studio 2017

environment:
  CTEST_OUTPUT_ON_FAILURE: ON

build_script:
- cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set "CMAKE_GENERATOR=Visual Studio 14"
- cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set "CMAKE_GENERATOR=Visual Studio 15"
- cmd: cmake -E make_directory build
- cmd: cmake -E chdir build cmake -G "%CMAKE_GENERATOR%" ..
- cmd: cmake --build build

test_script:
- cmd: REM cmake --build build --target test

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
